[area-study]

; CLASSIFICATION [UNCLASSIFIED, CUI, CONFIDENTIAL, SECRET, TOP SECRET, TOP SECRET//SCI]
CLASSIFICATION = UNCLASSIFIED

; Optional. Data directory to pull information from
; DATA_DIRECTORY = /data

; Save directory
SAVE_DIRECTORY = save

; enable/disable categories to plot
EMERGENCY_SERVICES = True
LAW_ENFORCEMENT = True
MILITARY = True
WATER = True
POWER = True
FOOD = True