[area-study]

; CLASSIFICATION [UNCLASSIFIED, CUI, CONFIDENTIAL, SECRET, TOP SECRET, TOP SECRET//SCI]
CLASSIFICATION = UNCLASSIFIED

; Optional. Data directory to pull information from
DATA_DIRECTORY = ./data

; Save directory
SAVE_DIRECTORY = save

GOOGLE_API_KEY =


LOCATION = 30.46017022522309, -97.90902118431548, 30.386231699038007, -97.81761149768143

; enable/disable categories to plot
EMERGENCY = False
LAW_ENFORCEMENT = False
MILITARY = False
WATER = False
POWER = False
FOOD = False
TRANSPORT = False
SERVICES = False
GOVERNMENT = False
STORES = False
SCHOOLS = False
TOURISM = False
SHELTER = False
BUILDING = False
TELECOM = False
MAN_MADE = False

CITY=Austin
STATE=Texas
COUNTRY_CODE=United States of America
CRIME_SODA_ADDR = https://data.austintexas.gov/resource/fdj4-gpfu.json
ZIPCODE_SODA_ADDR = https://data.austintexas.gov/resource/nf4y-c7ue.json