[area-study]

; CLASSIFICATION [UNCLASSIFIED, CUI, CONFIDENTIAL, SECRET, TOP SECRET, TOP SECRET//SCI]
CLASSIFICATION = UNCLASSIFIED

; Optional. Data directory to pull information from
; DATA_DIRECTORY = /data

GOOGLE_API_KEY = API_KEY

; Save directory
SAVE_DIRECTORY = save

LOCATION = 30.43387743923341, -97.86826464771093, 30.38296960905653, -97.80685780237778

; enable/disable categories to plot
EMERGENCY_SERVICES = True
LAW_ENFORCEMENT = True
MILITARY = True
WATER = True
POWER = True
FOOD = True